# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool: Default

variables: { agent.disablelogplugin.TestResultLogPlugin: 'false' }

steps:
- script: 
        docker build -t myimg2 .
        docker run myimg2